---
title: "Joins. Работа со строками. Пакет stringr"
---
# cbind, rbind

```{r}
g <- rnorm(50)
dim(g) <- c(5, 10)
g <- as.data.frame(g)
g

f <- rnorm(30)
dim(f) <- c(3, 10)
f <- as.data.frame(f)
f


rbind(g, f)

h <- rnorm(21)
dim(h) <- c(3, 7)
h <- as.data.frame(h)
h

cbind(f, h)

# cbind.data.frame()
# rbind.data.frame()
```

# Joins
```{r}
languages <- data.frame(
  languages = c("Selkup", "Itelmen", "Chukchi", "Kashubian"),
  countries = c("Russia", "Russia", "Russia", "Poland"),
  iso = c("sel", "itl", "ckt", "pol"))
languages

country_population <- data.frame(
  countries = c("Russia", "Poland", "Finland"),
  population = c(143, 38, 5))
country_population

# install.packages("dplyr")
library(dplyr)
inner_join(languages, country_population)
#semi_join(country_population, languages) -> df
# str(df)
left_join(languages, country_population)
right_join(languages, country_population)
anti_join(languages, country_population)

full_join(country_population, languages)
```

# Strings
```{r}
paste("mm", "ff")
paste0("mm", "ff")
```

