---
title: "Визуализация данных. Пакет ggplot2 и его расширения. Пакет plotly. R Markdown. R Notebook. Shiny"
---
## Фасетизация
```{r}
chi.kuk <- read.csv("http://goo.gl/Zjr9aF")
adyghe <- read.csv("https://goo.gl/rYZPIj", sep = "\t")
library(tidyverse)
str(adyghe)
adyghe2 <- adyghe[,-1]        
adyghe %>%
  ggplot(aes(F1, fill = vowel)) ->
  my_plot

my_plot

my_plot +
geom_histogram(data = adyghe2, fill = "lightgrey") +
geom_histogram()+
facet_wrap(~vowel, nrow = 2)+
guides(fill = FALSE) +                              # убирает легенду
theme_bw()                                         # черно-белая тема

```

## ggplot extensions
[ggplot extensions gallery](http://www.ggplot2-exts.org/gallery/)
```{r, eval = F}
install.packages("devtools")
devtools::install_github("dgrtwo/gganimate")
install.packages('ggthemes', dependencies = TRUE)
```

## Plotly
[подробнее см. здесь](https://plot.ly/r/)
```{r, eval=F}
install.packages("plotly")
```

## Flex Dashboards
[подробнее см. здесь](http://rmarkdown.rstudio.com/flexdashboard/)
```{r, eval = F}
install.packages("flexdashboard")
```

## Shiny
[подробнее см. здесь](http://shiny.rstudio.com/gallery/)
```{r, eval = F}
install.packages("shiny")
```
