---
title: "Визуализация данных. Пакет ggplot2 и его расширения. Пакет plotly. R Markdown. R Notebook. Shiny"
---

```{r}
library(tidyverse)
chi.kuk <- read.csv("http://goo.gl/Zjr9aF")
ggplot(data = chi.kuk, aes(x = chi.kuk$s.duration.ms, y = chi.kuk$vowel.duration.ms)) +
  geom_smooth() +
  geom_point()
```
```{r}
ggplot(data = chi.kuk, aes(x = chi.kuk$s.duration.ms, y = chi.kuk$vowel.duration.ms)) +
  geom_smooth(aes(color = "red")) +
  geom_point()

```

```{r}
ggplot(data = chi.kuk, aes(x = chi.kuk$s.duration.ms, y = chi.kuk$vowel.duration.ms)) +
  geom_smooth() +
  geom_point(aes(color = "red"))

```
```{r}
ggplot(data = chi.kuk, aes(x = chi.kuk$s.duration.ms, y = chi.kuk$vowel.duration.ms, color = "red")) +
  geom_smooth() +
  geom_point()

```
```{r}
plot(1:25, pch = 1:25)
```

```{r}
plot(chi.kuk$s.duration.ms, chi.kuk$vowel.duration.ms,
  cex = chi.kuk$age)
# :( not really cool 
```


```{r}
chi.kuk %>%
  ggplot(aes(s.duration.ms, vowel.duration.ms, size = age)) +
  geom_point()

```

```{r}
chi.kuk %>% 
  ggplot(aes(s.duration.ms, vowel.duration.ms, color = orientation))+
  geom_point()+
  geom_rug()
```

```{r}
df <- data.frame(names = c(
  rep("Маша", 50),
  rep("Саша", 40),
  rep("Василиса", 10)
))

df
```
```{r}
df %>% 
  ggplot(aes(names)) +
  geom_bar()
```

```{r}
df <- data.frame(names = c("Маша", "Саша", "Василиса"), 
                 number = c(50, 40, 10))

df
```

```{r}
df %>% 
  ggplot(aes(names, number))+
  geom_bar(stat = "identity")
```

```{r}
str(mpg)
```
```{r}
mpg %>%
  ggplot(aes(class, hwy, 
             fill = factor(year)))+
  geom_violin()+
  labs(title = "Гончарное дело",
       subtitle = "Грачи улетели, метро еще ходит",
       caption = "данные взяты из головы")+  theme_bw()
```
```{r, eval = FALSE}
?pie
```

