---
title: "Описательная статистика"
---

## Делим на группы непрерывную переменную
```{r}
a <- sin(1:100)
b <- c(-1, -0.5, 0, 0.5, 1)
table(cut(a, breaks = b))
```

## Взвешенное средние
```{r}
weighted.mean(x = c(10, 9, 9),
              w = c(0.6, 0.2, 0.2))
```

## SD
```{r}
set.seed(42)
a <- runif(40)
mean(a)
plot(a)
abline(h = mean(a))
```
```{r}
a - mean(a)
(a - mean(a))^2
sum((a - mean(a))^2)/length(a) # средние
(sum((a - mean(a))^2)/length(a))^(1/2)
(sum((a - mean(a))^2)/(length(a)-1))^(1/2)
sd(a) == (sum((a - mean(a))^2)/(length(a)-1))^(1/2)
```

## Квантиль
```{r}
quantile(a, 0.4)
```

### Таблицы сопряженности
```{r}
v <- c('m', 'f', 'm', 'm', 'f', 'f', 'f', 'f')
df <- data.frame(sex = c('m', 'f', 'm', 'm', 'f', 'f', 'f', 'f'),
hand = c('lf', 'rh', 'rh', 'rh', 'rh', 'lf', 'am', 'rh'))
table(v)
table(df)
prop.table(table(v))
prop.table(c(1, 2))
prop.table(table(df))

prop.table(table(df))*100

round(prop.table(table(df))*100)
```


```{r, warning=FALSE, message=FALSE}
library(tidyverse)
words <- read_csv("https://goo.gl/a4xNwj")
words <- c(words$trans_english, words$trans_russian)
words <-sapply(words, function(x){unlist(strsplit(x, ",| "))[1]})
words <- data.frame(words = words)
str(words)
words$n_char <- nchar(as.character(words$words))
str(words)
nrow(words)
words$language <- rep(c("eng", "rus"), each = 1310)
str(words)

words %>%
  group_by(language) %>%
  summarise(my.mean = mean(n_char),
            my.min = mean(n_char) - sd(n_char),
            my.max = mean(n_char) + sd(n_char)) %>% 
  ggplot(aes(x = language, y = my.mean, fill = language))+
  geom_bar(stat = "identity")+
  theme_bw()+
  geom_errorbar(aes(ymin = my.min, ymax = my.max), width = 0.2, color = "green")+
  xlab("языки")+
  ylab("количество символов в слове")+
  labs(title = "Это невероятно интересный график")+ 
  guides(fill=FALSE)
```
